Cleanup

diff --git a/.github/workflows/ci-e2e-tests.yml b/.github/workflows/ci-e2e-tests.yml
--- a/.github/workflows/ci-e2e-tests.yml
+++ b/.github/workflows/ci-e2e-tests.yml
@@ -94,6 +94,7 @@ jobs:
       
       - name: Validate that Kardinal manager applied the changes
         run: |
+          # Check that the four prod service pods are running and ready
           while [ $(kubectl get pods -n prod -o custom-columns=NAMESPACE:metadata.namespace,POD:metadata.name,PodIP:status.podIP,READY-true:status.containerStatuses[*].ready | grep "true,true" | wc -l) -ne 4 ]
           do
               echo "Waiting for prod pods to run..."
@@ -102,9 +103,13 @@ jobs:
               sleep 10
           done
           kubectl get pods -n prod
+
+          # Check the right services are running.
           apps=$(kubectl get pods -n prod -o custom-columns=:metadata.labels.app | tr " " "\n" | sort -g | tr "\n" " " | xargs)
           echo ${apps}
           if [ "${apps}" != "cartservice frontend postgres productcatalogservice" ]; then exit 1; fi
+        
+          # Check for errors in the kardinal manager logs
           if kubectl logs -n default -l dev.kardinal.app-id=kardinal-manager | grep "ERRO"
           then
             echo "Errors found in the kardinal manager"
@@ -117,21 +122,20 @@ jobs:
           cat kardinal.out
           flow_id=$(grep "Flow.*created" kardinal.out | cut -d ' ' -f2 | tr -d "\"")
           KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli flow ls | grep ${flow_id}
+          
+          # Check that the dev service pod is running and ready
           while ! kubectl get pods -n prod -o custom-columns=NAMESPACE:metadata.namespace,POD:metadata.name,PodIP:status.podIP,READY-true:status.containerStatuses[*].ready | grep true | grep "frontend-${flow_id}"
           do
               echo "Waiting for dev frontend pod to run..."
-              kubectl get pods -n prod
+              kubectl get pods -n prod -o custom-columns=NAMESPACE:metadata.namespace,POD:metadata.name,PodIP:status.podIP,READY-true:status.containerStatuses[*].ready
               ((c++)) && ((c==12)) && exit 1
               sleep 10
           done
           kubectl get pods -n prod
-          #KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli gateway ${flow_id} > kardinal.out
-          #cat kardinal.out
-          #flow_url=$(grep "http" kardinal.out | awk '{print $NF}'
-          #status_code=$(curl -s -o /dev/null -w "%{http_code}" ${flow_url})
-          #echo "${flow_url} returned status code ${status_code}"
-          #if [ "${status_code}" != "200" ]; then exit 1; fi
+          
           KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli flow delete ${flow_id}
+        
+          # Check for errors in the kardinal manager logs
           if kubectl logs -n default -l dev.kardinal.app-id=kardinal-manager | grep "ERRO"
           then
             echo "Errors found in the kardinal manager"
@@ -146,9 +150,28 @@ jobs:
       - name: Create flow with template and delete flow
         run: |
           KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli flow create frontend kurtosistech/frontend:demo-frontend  --template-args ci/template_args.yaml --template extra-item-shared > kardinal.out
+          cat kardinal.out
           flow_id=$(grep "Flow.*created" kardinal.out | cut -d ' ' -f2 | tr -d "\"")
           KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli flow ls | grep ${flow_id}
+          
+          # Check that the dev service pod is running and ready
+          while ! kubectl get pods -n prod -o custom-columns=NAMESPACE:metadata.namespace,POD:metadata.name,PodIP:status.podIP,READY-true:status.containerStatuses[*].ready | grep true | grep "frontend-${flow_id}"
+          do
+              echo "Waiting for dev frontend pod to run..."
+              kubectl get pods -n prod -o custom-columns=NAMESPACE:metadata.namespace,POD:metadata.name,PodIP:status.podIP,READY-true:status.containerStatuses[*].ready
+              ((c++)) && ((c==12)) && exit 1
+              sleep 10
+          done
+          kubectl get pods -n prod
+
           KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli flow delete ${flow_id}
+
+          # Check for errors in the kardinal manager logs
+          if kubectl logs -n default -l dev.kardinal.app-id=kardinal-manager | grep "ERRO"
+          then
+            echo "Errors found in the kardinal manager"
+            kubectl logs -n default -l dev.kardinal.app-id=kardinal-manager | grep "ERRO"
+          fi
       
       - name: Delete template
         run: |
