Kardinal manager and trace router checks

diff --git a/.github/workflows/ci-e2e-tests.yml b/.github/workflows/ci-e2e-tests.yml
--- a/.github/workflows/ci-e2e-tests.yml
+++ b/.github/workflows/ci-e2e-tests.yml
@@ -90,6 +90,28 @@ jobs:
         run: |
           KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli manager deploy local-minikube
 
+          # Check that the three service pods are running and ready
+          while [ $(kubectl get pods -n default -o custom-columns=NAMESPACE:metadata.namespace,POD:metadata.name,PodIP:status.podIP,READY-true:status.containerStatuses[*].ready | grep "true,true" | wc -l) -ne 3 ]
+          do
+              echo "Waiting for kardinal manager pods to run..."
+              kubectl get pods -n default -o custom-columns=NAMESPACE:metadata.namespace,POD:metadata.name,PodIP:status.podIP,READY-true:status.containerStatuses[*].ready
+              ((c++)) && ((c==12)) && exit 1
+              sleep 10
+          done
+          kubectl get pods -n default
+
+          # Check the right services are running.
+          apps=$(kubectl get pods -n default -o custom-columns=:metadata.labels.app | tr " " "\n" | sort -g | tr "\n" " " | xargs)
+          echo ${apps}
+          if [ "${apps}" != "kardinal-manager trace-router trace-router-redis" ]; then exit 1; fi
+          
+          # Check for errors in the kardinal manager logs
+          if kubectl logs -n default -l dev.kardinal.app-id=kardinal-manager | grep "ERRO"
+          then
+            echo "Errors found in the kardinal manager"
+            kubectl logs -n default -l dev.kardinal.app-id=kardinal-manager | grep "ERRO"
+          fi
+ 
       - name: Deploy boutique demo manifest
         run: |
           KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli deploy -k ci/obd-demo.yaml
@@ -120,10 +142,6 @@ jobs:
 
       - name: Start gateway to the baseline flow and validate access
         run: |
-          kubectl get namespaces
-          kubectl describe namespace baseline
-          kubectl describe namespace istio-system
-          kubectl get namespaces -l kardinal.dev=enabled
           KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli gateway baseline > kardinal.out &
           while ! grep "Proxy server for host" kardinal.out
           do
@@ -136,6 +154,13 @@ jobs:
           status_code=$(curl -s -o /dev/null -w "%{http_code}" ${flow_url})
           echo "${flow_url} returned status code ${status_code}"
           if [ "${status_code}" != "200" ]; then exit 1; fi
+
+          # Check for errors in the trace router logs
+          if kubectl logs -n default -l app=trace-router | grep "ERRO"
+          then
+            echo "Errors found in the trace router"
+            kubectl logs -n default -l app=trace-router | grep "ERRO"
+          fi
 
       - name: Create, validate and delete flow
         run: |
@@ -153,7 +178,28 @@ jobs:
               sleep 10
           done
           kubectl get pods -n baseline
+         
+          # Start gateway to the flow and validate access
+          KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli gateway ${flow_id} > kardinal.out &
+          while ! grep "Proxy server for host" kardinal.out
+          do
+              echo "Waiting for gateway to start..."
+              cat kardinal.out
+              ((c++)) && ((c==12)) && exit 1
+              sleep 10
+          done
+          flow_url=$(grep "http" kardinal.out | awk '{print $NF}')
+          status_code=$(curl -s -o /dev/null -w "%{http_code}" ${flow_url})
+          echo "${flow_url} returned status code ${status_code}"
+          if [ "${status_code}" != "200" ]; then exit 1; fi
           
+          # Check for errors in the trace router logs
+          if kubectl logs -n default -l app=trace-router | grep "ERRO"
+          then
+            echo "Errors found in the trace router"
+            kubectl logs -n default -l app=trace-router | grep "ERRO"
+          fi
+ 
           KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli flow delete ${flow_id}
         
           # Check for errors in the kardinal manager logs
@@ -220,3 +266,18 @@ jobs:
             echo "Errors found in the kardinal manager"
             kubectl logs -n default -l dev.kardinal.app-id=kardinal-manager | grep "ERRO"
           fi
+      
+      - name: Remove kardinal manager
+        run: |
+          KARDINAL_CLI_DEV_MODE=TRUE /tmp/kardinal-cli manager remove > kardinal.out
+
+          # Check that the services have been terminated
+          while [ "$(kubectl get pods -n default 2>&1 >/dev/null)" != "No resources found in default namespace." ]
+          do
+              echo "Waiting for the services to terminate..."
+              kubectl get pods -n default
+              ((c++)) && ((c==12)) && exit 1
+              sleep 10
+          done
+          kubectl get pods -n default
+ 
